/*
 * HelloWorldLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.HelloworldController;
const HelloWorldResponse = testerlib.HelloWorldResponse;

describe("HelloworldController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Testcase for testing endpoint Helloworld_GET
     */
    it("should testHelloworldGET1 response", function testHelloworldGET1Test(done) {
        controller.getHelloworldGET(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            assert.isNotNull(response);
            assert.equal('{  "message": "Hello world"}', context.response.body);
            done();
        });
    });

});
